"""reformat Quiz

Revision ID: 057dda34667b
Revises: 4a14e49a9596
Create Date: 2023-09-24 18:14:20.119105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "057dda34667b"
down_revision: Union[str, None] = "4a14e49a9596"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Question", sa.Column("quizId", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Question", "Quiz", ["quizId"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Question", type_="foreignkey")
    op.drop_column("Question", "quizId")
    # ### end Alembic commands ###
