"""add Question

Revision ID: 4cd538eef9a8
Revises: d1c1b8579435
Create Date: 2023-09-24 16:53:32.652213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cd538eef9a8"
down_revision: Union[str, None] = "d1c1b8579435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Question",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Answer", sa.Column("questionId", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Answer", "Question", ["questionId"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Answer", type_="foreignkey")
    op.drop_column("Answer", "questionId")
    op.drop_table("Question")
    # ### end Alembic commands ###
