"""'addNullableInEmail'

Revision ID: 63e9251d2b45
Revises: 746969af1aba
Create Date: 2023-09-19 18:54:11.388054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63e9251d2b45"
down_revision: Union[str, None] = "746969af1aba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "User", ["userName"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="unique")
    # ### end Alembic commands ###
