"""add Quiz

Revision ID: 6869097f971c
Revises: 4cd538eef9a8
Create Date: 2023-09-24 17:00:41.845104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6869097f971c"
down_revision: Union[str, None] = "4cd538eef9a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Quiz",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("authorId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorId"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Quiz")
    # ### end Alembic commands ###
