"""'add-rndstr-column-in-User'

Revision ID: 6b459b041c9f
Revises: 75a26848d1f9
Create Date: 2024-02-01 18:14:57.707432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b459b041c9f'
down_revision: Union[str, None] = '75a26848d1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('rndstr', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'User', ['rndstr'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'rndstr')
    # ### end Alembic commands ###
