"""'del-firstname-and-lastname-in-user-table'

Revision ID: 75a26848d1f9
Revises: 48690cb182e0
Create Date: 2023-11-24 17:31:10.564301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a26848d1f9'
down_revision: Union[str, None] = '48690cb182e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'firstName')
    op.drop_column('User', 'lastName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
