"""removeQuizResultsRelationship


Revision ID: 8349f456c3df
Revises: 9602361b1226
Create Date: 2023-11-02 16:37:25.278560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8349f456c3df"
down_revision: Union[str, None] = "9602361b1226"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("QuizResults", sa.Column("userId", sa.Integer(), nullable=True))
    op.add_column("QuizResults", sa.Column("quizId", sa.Integer(), nullable=True))
    op.drop_constraint("QuizResults_quiz_fkey", "QuizResults", type_="foreignkey")
    op.drop_constraint("QuizResults_user_fkey", "QuizResults", type_="foreignkey")
    op.create_foreign_key(
        None, "QuizResults", "Quiz", ["quizId"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "QuizResults", "User", ["userId"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("QuizResults", "user")
    op.drop_column("QuizResults", "quiz")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "QuizResults",
        sa.Column("quiz", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "QuizResults",
        sa.Column("user", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "QuizResults", type_="foreignkey")
    op.drop_constraint(None, "QuizResults", type_="foreignkey")
    op.create_foreign_key(
        "QuizResults_user_fkey",
        "QuizResults",
        "User",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "QuizResults_quiz_fkey",
        "QuizResults",
        "Quiz",
        ["quiz"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("QuizResults", "quizId")
    op.drop_column("QuizResults", "userId")
    # ### end Alembic commands ###
