"""'fixedBagQuizResult'

Revision ID: 9602361b1226
Revises: 95d72e75cae4
Create Date: 2023-11-01 23:42:50.039939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9602361b1226"
down_revision: Union[str, None] = "95d72e75cae4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("QuizResults_quiz_fkey", "QuizResults", type_="foreignkey")
    op.create_foreign_key(
        None, "QuizResults", "Quiz", ["quiz"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "QuizResults", type_="foreignkey")
    op.create_foreign_key(
        "QuizResults_quiz_fkey",
        "QuizResults",
        "User",
        ["quiz"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
