"""add isadmin

Revision ID: bc9af4e8ef48
Revises: 6b459b041c9f
Create Date: 2024-02-04 18:26:27.909246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9af4e8ef48'
down_revision: Union[str, None] = '6b459b041c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'isAdmin')
    # ### end Alembic commands ###
