"""add ondelete cascade in question

Revision ID: c6be7d2ced1d
Revises: 057dda34667b
Create Date: 2023-09-28 19:26:11.427016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6be7d2ced1d"
down_revision: Union[str, None] = "057dda34667b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Question_quizId_fkey", "Question", type_="foreignkey")
    op.create_foreign_key(
        None, "Question", "Quiz", ["quizId"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Question", type_="foreignkey")
    op.create_foreign_key(
        "Question_quizId_fkey", "Question", "Quiz", ["quizId"], ["id"]
    )
    # ### end Alembic commands ###
