version: "3.9"

services:
  dq-server:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
    - ./back-end:/back-end
    command: >
      bash -c
      "
      uvicorn main:app --reload --host 0.0.0.0 --port 8080
      "
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      REDIS_HOST: redis
    env_file:
      - ./back-end/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./dumpUTF8.sql:/docker-entrypoint-initdb.d/dumpUTF8.sql
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  dq-client:
    build: 
      context: ./front-endv2
      dockerfile: Dockerfile
    volumes:
      - ./front-endv2:/front-end
    command: >
      bash -c
      "
      cd frontapp
      &&
      npm start
      "
    ports:
      - "80:3000"
    depends_on:
      - dq-server
volumes:
  postgres_data:
  usr-data:
